## Numpy array and basics 
Learn about numpy with Nishu

#### Vector

[1,2,3,4,5,6] 

#### Matrices

[
    [1, 2, 3],
    [4, 5, 6]
]

In [1]:
import numpy as np 
import time

### creating array from list

In [2]:
arr_1d = np.array([1,2,3,4,5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2D array: ", arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


#### numpy array take list as input hence if we inputed the 2d array like this it will show error

In [3]:
arr_2d = np.array([1,2,3],[4,5,6])
print("2D array: ", arr_2d)

TypeError: Field elements must be 2- or 3-tuples, got '4'

### List vs numpy array

In [4]:
py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)
# [1, 2,3,1,2,3]

np_array = np.array([1,2,3])
print("Python array multiplication ",np_array * 2)
#scalar multiplication, get complex as the dimension of the array increases
#element wise multiplication

start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

# now lets multiply numpy array
start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)


Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]

 List operation time:  0.0665738582611084

 Numpy operation time:  0.005071878433227539


### We can see that numpy array multiplication is very fast 


### Creating array from scratch

In [5]:
zeros = np.zeros((3,4))
print("zeros array: \n", zeros)

# one array
ones = np.ones((2,3))
print("one array: \n", ones)

#constant array : when we need an array of special constant
full = np.full((2,2),7)
print("full array: \n",full)

# randomness
# random is a class which has lot of methods
random = np.random.random((2,3))
print("random array: \n", random)

# Sequence
# range is non inclusive outer boundary
sequence = np.arange(0, 10, 2) #2 is step size
print("sequence array: \n", sequence)


zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
one array: 
 [[1. 1. 1.]
 [1. 1. 1.]]
full array: 
 [[7 7]
 [7 7]]
random array: 
 [[0.12604745 0.09222172 0.25825421]
 [0.91749632 0.75435184 0.20249362]]
sequence array: 
 [0 2 4 6 8]


### Vector, Matrix and Tensor


In [6]:
vector1 = np.array([1, 2, 3])
print("Vector: ", vector1)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix: ", matrix)

tensor = np.array([[[1,2], [3,4]],
                   [[5,6], [7,8]]])
# multidimensional array are called tensor
print("Tensor: ",tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array properties


In [ ]:
arr = np.array([[1,2,3],
                [4,5,6]])
# but using True is not the ideal representation, numpy operation are optimized because there is similar data structure

print("Shape ", arr.shape)
print("Dimension", arr.ndim)
print("Size ",arr.size)
print("DType", arr.dtype)

Shape  (2, 3)
Dimension 2
Size  6
DType int64


### Array reshaping

In [ ]:
arr = np.arange(12)
print("Orginal array ", arr)

reshaped = arr.reshape((3, 4))
# 3 rows and 4 column
print("\n Reshaped array ", reshaped)

flattened = reshaped.flatten()
print("\n Flattened array ", flattened)

# return view instead of copy: hence return the orginal array
raveled = reshaped.ravel()
print("\n raveled array ", raveled)

# Transpose 
transpose = reshaped.T
print("\n Transposed array ", transpose)

Orginal array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
