## Numpy Array Operations

In [3]:
import numpy as np 

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic Slicing", arr[2:7])
print("With Step", arr[1:8:2]) 
# every second position
print("Negative indexing", arr[-1])

Basic Slicing [3 4 5 6 7]
With Step [2 4 6 8]


### Now the question arises what would we have done if it was 2D array

In [14]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific element", arr_2d[1,2])
# targeting a row
print("Entire row: ", arr_2d[1])
# all row but we target some column
print("printing ",arr_2d[:, 1])

Specific element 6
Entire row:  [4 5 6]
printing  [2 5 8]


## Sorting

In [ ]:
unsorted = np.array([3,1,4,1,5,9,2,6])
print("Sorted array", np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print("Sorted 2D array by column \n", np.sort(arr_2d_unsorted, axis=0))
# axis = 1 , row wise sorted 
# axis = 0 top to bottom sorted

Sorted array [1 1 2 3 4 5 6 9]
Sorted 2D array by column 
 [[1 1]
 [2 2]
 [3 3]]


### Filter

In [21]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0] #allow us to write an expression which is evaluated
print("Even numbers", even_number)

Even numbers [ 2  4  6  8 10]


### Filter with mask

In [22]:
mask = numbers > 5
print("Numbers greater than 5", numbers[mask])

Numbers greater than 5 [ 6  7  8  9 10]


## Fancy indexing Vs np.where()

In [23]:
indices = [0, 2, 4]

In [26]:
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result) # see how the where_result is printing
print("NP where", numbers[where_result])

[1 3 5]
(array([5, 6, 7, 8, 9]),)
NP where [ 6  7  8  9 10]


In [30]:
condition_array = np.where(numbers > 5, "true", "false")
# x and y , see the documentation
# where ever the no. was greater than 5 we have printed true otherwuise false
print(condition_array) 

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


In [32]:
# if(numbers > 5):
#     numbers*4
# else:
#     numbers



### Adding and Removing Data

In [34]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = arr1 + arr2
# wrong
print(combined)
combined = np.concatenate((arr1, arr2))
print(combined)


[5 7 9]
[1 2 3 4 5 6]


### Array Compatability

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6,8])
c = np.array([7,8,9])

# operation where the shape of both the arrays should be same
print("Compatability shapes", a.shape == b.shape)

Compatability shapes False


In [40]:
orginal = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])
# mixing two arrays
# vstack always add row 
with_new_row = np.vstack((orginal, new_row))
print(orginal)
print(with_new_row)

new_col = np.array([[7],[8]])
# hstack add new column
with_new_col = np.hstack((orginal, new_col))
print("With new column \n", with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
With new column 
 [[1 2 7]
 [3 4 8]]


In [ ]:
# Delete operation take care of indexing
arr = np.array([1,2,3,4,5])
deleted = np.delete(arr,2)
print(deleted) # print the array not the delted element

[1 2 4 5]
